### ISSUE TITLE
Fatal unhandled exception

### ISSUE THREAD

**Issue by PlayWithArt** [smilefam/SendBird-SDK-dotNET#3]
Got this after upgrading to 3.0.2 from 3.0.1

12-13 13:22:24.603 E/mono-rt (15561): [ERROR] FATAL UNHANDLED EXCEPTION: System.Exception: Stopped.
12-13 13:22:24.603 E/mono-rt (15561):   at SendBird.CountDownTimer+_CountDownTimer.Run () [0x00049] in <5b4a646a7de54f2bb48f8ccbe4519cee>:0 
12-13 13:22:24.603 E/mono-rt (15561):   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00017] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/thread.cs:68 
12-13 13:22:24.603 E/mono-rt (15561):   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x0008d] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957 
12-13 13:22:24.603 E/mono-rt (15561):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904 
12-13 13:22:24.603 E/mono-rt (15561):   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00031] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893 
12-13 13:22:24.603 E/mono-rt (15561):   at System.Threading.ThreadHelper.ThreadStart () [0x0000b] in /Users/builder/data/lanes/3511/77cb8568/source/mono/mcs/class/referencesource/mscorlib/system/threading/thread.cs:105

**Comment by sf-harry-kim** [comment]
This issue has been resolved on v3.0.3.
Sorry for the inconvenience.
